name: CI

on:
  push:
    paths-ignore:
    - '**/*.md'
    - 'etc/*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    timeout-minutes: 3
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        emacs-version:
          - "29.1"
        experimental: [false]
        include:
          - os: ubuntu-latest
            emacs-version: snapshot
            experimental: true
          - os: macos-latest
            emacs-version: snapshot
            experimental: true
          - os: windows-latest
            emacs-version: snapshot
            experimental: true
    steps:
    - uses: cachix/install-nix-action@v21
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          accept-flake-config = true
    - name: Checkout repo
      uses: actions/checkout@v4
    - uses: jcs090218/setup-emacs@master
      with:
        version: ${{ matrix.emacs-version }}
    - uses: emacs-eask/setup-eask@master
      with:
        version: 'snapshot'
    - name: Run tests
      run: make test
