name: Update emacs snapshots with flake

on:
  schedule:
    - cron: "15 10 * * 2"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v21
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Update emacs snapshots
      run: nix flake update
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        title: 'Emacs snapshots update'
        body: ''
        commit-message: 'Update emacs snapshots'
        branch: emacs-snapshot
        branch-suffix: timestamp
        delete-branch: true
        add-paths: flake*
